version: 5.0.{build}
branches:
  only:
  - release
  - master
  - dev
image: Visual Studio 2019
clone_depth: 1
init:
- ps: git version
environment:
  CI: true
  Appveyor: true
  COVERALLS_REPO_TOKEN: 
    secure: 5L1b6XqSNTOfU1iZrARo5eUOi1HOleVO3VDCW0pr6yaspgkC5jxL+gBDK0OEY8EI
  COVERALLS_REPO_TOKEN_GITLAB:
    secure: yPxFQv4kSWtZ7Vvs70bIXDx9IOEEJ9utI3UyZsJGU7rt63gZnHOry0kt9DBMWcwV
  CODECOV_TOKEN:
    secure: 6rKKLXCmy3HZBxW5SjoO4Ox7G09FC0NJgGnvukWkYyJ2rx1GCzu4JvmLin69SHRz
  CODECOV_TOKEN_GITLAB:
    secure: +22PuAn5seq4bbCVCly8zDFuyEV3m2NjW3QuM0+2gm4c8akwicNFmv2T/ZGd0Jpd
services:
- mssql2017
- mysql
- mongodb
install:
- ps: >-
    .\scripts\appveyor\appveyor.install.ps1
build_script:
- ps: >-
    .\scripts\appveyor\appveyor.build.ps1
test_script:
- ps: >-
    .\scripts\appveyor\appveyor.test.ps1
artifacts:
- path: src\admin\Bootstrap.Admin\bin\release\net5.0\publish\
  name: BootstrapAdmin
  type: WebDeployPackage
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: BootstrapAdmin-v$(appveyor_build_version)
  description: BootstrapAdmin auto generated by Appveyor
  auth_token:
    secure: bTF+J9xTuL63Q3fMN533GYvPEjHYPZsFRCVrpYpyFNcQpLe3CMLYT1D/x52J9nhC
  artifact: BootstrapAdmin
  draft: true
  prerelease: true
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
    APPVEYOR_REPO_PROVIDER: gitHub
notifications:
- provider: Email
  to:
  - argo@163.com
  subject: '{{projectName}} Build {{status}} {{buildVersion}}'
  message: >-
    <div style="font-family:'Segoe UI',Arial,Sans-Serif;font-size:10pt;">
        {{#passed}}
        <h1 style="font-size: 150%;font-weight:normal; color:#078DC7;"><a href="{{buildUrl}}" style="color:#078DC7;">Build {{projectName}} {{buildVersion}} completed</a></h1>{{/passed}}
        {{#failed}}
        <h1 style="font-size: 150%;font-weight:normal; color:#ff3228;"><a href="{{buildUrl}}" style="color:#ff3228;">Build {{projectName}} {{buildVersion}} failed</a></h1>{{/failed}}
        <p style="color: #888;">
            Commit <a href="{{commitUrl}}">{{commitId}}</a> by <a href="mailto:{{commitAuthorEmail}}">{{commitAuthor}}</a> on {{commitDate}}:
            <br />
            <span style="font-size: 110%;color:#222;">{{commitMessage}}</span>
        </p>
        <p><a href="{{notificationSettingsUrl}}" style="font-size:85%;color:#999;">Configure your notification preferences</a></p>
    </div>
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
