using Bootstrap.DataAccess.Helper;

namespace Microsoft.AspNetCore.Builder
{
    /// <summary>
    /// 自动生成数据库扩展操作类
    /// </summary>
    public static class AutoGenerateDatabaseExtensions
    {
        /// <summary>
        /// 自动生成数据库中间件
        /// </summary>
        /// <param name="app"></param>
        public static IApplicationBuilder UseAutoGenerateDatabase(this IApplicationBuilder app)
        {
            app.Use(async (context, next) =>
            {
                AutoDbHelper.CheckDB();
                await next();
            });
            return app;
        }
    }
}
