name: Docker Image CI

on:
  push:
    branches:
      - master-bak

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file src/blazor/admin/BootstrapAdmin.Web/Dockerfile --tag ba:$(date +%s)
